version: "3.8"

services:
  outlier-detector:
    image: lozioo/outlier-detector:latest
    restart: always

    # Needed for printing logs.
    stdin_open: true  # docker run -i
    tty: true         # docker run -t

    # Now the address "host.docker.internal" represents the host's 127.0.0.1.
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - MQTT_BROKER=host.docker.internal
      - SAMPLES_LEN=2
      - OUTLYING_SAMPLES_N=1

  hasher:
    image: lozioo/hasher:latest
    restart: always

    stdin_open: true
    tty: true

    extra_hosts:
      - "host.docker.internal:host-gateway"
