version: "3.8"

services:
  outlier-detector:
    image: lozioo/outlier-detector:latest
    restart: always

    # Needed for printing logs.
    stdin_open: true  # docker run -i
    tty: true         # docker run -t

    # Now the address "host.docker.internal" represents the host's 127.0.0.1.
    extra_hosts:
      - host.docker.internal:host-gateway

    environment:
      - MQTT_BROKER=host.docker.internal    # str:  IP address of the MQTT Broker.
      - RPC_ADDRESS=hasher                  # str:  IP address of the RPC hasher service.
      - SAMPLES_LEN=120                     # int:  Trigger transmission routine on that defined len(data).
      - OUTLYING_SAMPLES_N=6                # int:  (SAMPLES_LEN + 2 * OUTLYING_SAMPLES_N) samples, sort the list and remove OUTLYING_SAMPLES_N from the left and right.

  hasher:
    image: lozioo/hasher:latest
    restart: always

    stdin_open: true
    tty: true

    extra_hosts:
      - host.docker.internal:host-gateway

    volumes:
      - type: bind
        source: ./data
        target: /root/data

    environment:
      - RPC_ADDRESS=0.0.0.0                 # str:  IP address where the RPC server listens for incoming connections.
      - BLOCKCHAIN_ADDRESS=90.147.185.8     # str:  IP address of the blockchain.
      - DB_FILE=./data/hash.db.txt          # str:  Local DB file path.
