version: "3.8"

services:
  outlier-detector:
    image: lozioo/outlier-detector:latest
    restart: always

    # Now the address "host.docker.internal" represents the host's 127.0.0.1.
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - MQTT_BROKER=host.docker.internal
      - SAMPLES_LEN=3
      - OUTLYING_SAMPLES_N=3

  hasher:
    image: lozioo/hasher:latest

  hash-saver:
    image: lozioo/hash-saver:latest
