version: "3.8"

services:
  outlier-detector:
    image: lozioo/outlier-detector:latest
    restart: always
    network_mode: host

    environment:
      - MQTT_BROKER=127.0.0.1

  hasher:
    image: lozioo/hasher:latest

  hash-saver:
    image: lozioo/hash-saver:latest
